# Generated by Django 3.2 on 2021-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facepic',
            old_name='face_id',
            new_name='face',
        ),
        migrations.RenameField(
            model_name='facepic',
            old_name='pic_id',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='foldercover',
            old_name='folder_id',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='foldercover',
            old_name='pic_id',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='tagcover',
            old_name='pic_id',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='tagcover',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='facepic',
            unique_together={('pic', 'face')},
        ),
        migrations.AlterUniqueTogether(
            name='foldercover',
            unique_together={('folder', 'pic')},
        ),
        migrations.AlterUniqueTogether(
            name='tagcover',
            unique_together={('pic', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag')},
        ),
    ]
