# Generated by Django 3.2 on 2021-04-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_auto_20210418_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='folder_id',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
